// Comprehensive US University and Course Code Database
// Used by upload.html and browse.html for autocomplete/filtering

const UNIVERSITIES = [
  // Ivy League
  "Harvard University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Pennsylvania",
  "Brown University",
  "Dartmouth College",
  "Cornell University",

  // Big Ten
  "University of Michigan",
  "Michigan State University",
  "Ohio State University",
  "Penn State University",
  "University of Wisconsin-Madison",
  "University of Minnesota",
  "University of Iowa",
  "University of Illinois Urbana-Champaign",
  "Northwestern University",
  "Purdue University",
  "Indiana University Bloomington",
  "University of Nebraska-Lincoln",
  "University of Maryland",
  "Rutgers University",
  "University of Oregon",
  "University of Washington",
  "UCLA",
  "USC",

  // SEC
  "University of Alabama",
  "Auburn University",
  "University of Florida",
  "University of Georgia",
  "Louisiana State University",
  "University of Tennessee",
  "University of Kentucky",
  "University of South Carolina",
  "University of Mississippi",
  "Mississippi State University",
  "University of Arkansas",
  "Vanderbilt University",
  "University of Missouri",
  "Texas A&M University",
  "University of Texas at Austin",
  "University of Oklahoma",

  // ACC
  "Duke University",
  "University of North Carolina at Chapel Hill",
  "NC State University",
  "Wake Forest University",
  "University of Virginia",
  "Virginia Tech",
  "Georgia Tech",
  "Florida State University",
  "University of Miami",
  "Clemson University",
  "Boston College",
  "Syracuse University",
  "University of Pittsburgh",
  "University of Louisville",
  "Stanford University",
  "University of California, Berkeley",
  "Southern Methodist University",

  // Big 12
  "Baylor University",
  "Texas Christian University",
  "Texas Tech University",
  "University of Kansas",
  "Kansas State University",
  "Iowa State University",
  "Oklahoma State University",
  "West Virginia University",
  "University of Cincinnati",
  "University of Houston",
  "Brigham Young University",
  "University of Central Florida",
  "University of Colorado Boulder",
  "Arizona State University",
  "University of Arizona",
  "University of Utah",

  // Pac-12 / West Coast
  "University of Southern California",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of California, Davis",
  "University of California, Santa Barbara",
  "University of California, Irvine",
  "University of California, Santa Cruz",
  "University of California, Riverside",
  "University of California, Merced",
  "California Polytechnic State University",
  "San Diego State University",
  "San Jose State University",
  "California State University, Fullerton",
  "California State University, Long Beach",
  "California State University, Northridge",
  "California State University, Sacramento",
  "California State University, Los Angeles",
  "California State University, Fresno",
  "California State University, San Bernardino",
  "San Francisco State University",
  "Oregon State University",
  "Washington State University",
  "University of Nevada, Las Vegas",
  "University of Nevada, Reno",
  "University of Hawaii at Manoa",
  "Boise State University",

  // Top Private Universities
  "Massachusetts Institute of Technology",
  "California Institute of Technology",
  "Carnegie Mellon University",
  "Johns Hopkins University",
  "Rice University",
  "Emory University",
  "Georgetown University",
  "New York University",
  "University of Chicago",
  "Washington University in St. Louis",
  "Tufts University",
  "Brandeis University",
  "Case Western Reserve University",
  "University of Rochester",
  "Lehigh University",
  "Villanova University",
  "Santa Clara University",
  "Pepperdine University",
  "Gonzaga University",
  "Tulane University",
  "Northeastern University",
  "Boston University",
  "George Washington University",
  "American University",
  "Drexel University",
  "Stevens Institute of Technology",
  "Rensselaer Polytechnic Institute",
  "Worcester Polytechnic Institute",
  "Rose-Hulman Institute of Technology",

  // Major State Universities
  "University of Connecticut",
  "University of Massachusetts Amherst",
  "University of Vermont",
  "University of New Hampshire",
  "University of Maine",
  "University of Rhode Island",
  "University of Delaware",
  "Stony Brook University",
  "University at Buffalo",
  "University at Albany",
  "Binghamton University",
  "Temple University",
  "University of North Carolina at Charlotte",
  "University of North Carolina at Greensboro",
  "East Carolina University",
  "Appalachian State University",
  "College of William & Mary",
  "James Madison University",
  "George Mason University",
  "Old Dominion University",
  "Virginia Commonwealth University",
  "University of South Florida",
  "Florida International University",
  "Florida Atlantic University",
  "University of North Florida",
  "Georgia State University",
  "Kennesaw State University",
  "University of Alabama at Birmingham",
  "University of Alabama in Huntsville",
  "Middle Tennessee State University",
  "University of Memphis",
  "University of Louisville",
  "Western Kentucky University",
  "Northern Kentucky University",
  "University of Dayton",
  "Miami University (Ohio)",
  "Ohio University",
  "Bowling Green State University",
  "Kent State University",
  "University of Akron",
  "Wright State University",
  "Ball State University",
  "Indiana University-Purdue University Indianapolis",
  "University of Wisconsin-Milwaukee",
  "University of Wisconsin-Green Bay",
  "Marquette University",
  "University of Northern Iowa",
  "Drake University",
  "Creighton University",
  "University of South Dakota",
  "North Dakota State University",
  "University of North Dakota",
  "Montana State University",
  "University of Montana",
  "University of Wyoming",
  "Colorado State University",
  "University of Denver",
  "University of Colorado Denver",
  "University of Colorado Colorado Springs",
  "New Mexico State University",
  "University of New Mexico",
  "Northern Arizona University",
  "University of Idaho",
  "Portland State University",
  "University of Portland",
  "Western Washington University",
  "Eastern Washington University",
  "Central Washington University",
  "University of Alaska Anchorage",

  // Texas Schools
  "University of Texas at Dallas",
  "University of Texas at San Antonio",
  "University of Texas at Arlington",
  "University of Texas at El Paso",
  "University of North Texas",
  "Texas State University",
  "Sam Houston State University",
  "Lamar University",
  "Stephen F. Austin State University",
  "Prairie View A&M University",

  // HBCUs
  "Howard University",
  "Spelman College",
  "Morehouse College",
  "Hampton University",
  "Tuskegee University",
  "Florida A&M University",
  "North Carolina A&T State University",
  "Morgan State University",
  "Clark Atlanta University",
  "Xavier University of Louisiana",
  "Tennessee State University",
  "Jackson State University",
  "Southern University",
  "Grambling State University",
  "Alabama A&M University",
  "Alabama State University",
  "Delaware State University",
  "Bowie State University",
  "Coppin State University",
  "Norfolk State University",
  "Virginia State University",
  "South Carolina State University",
  "Bethune-Cookman University",
  "Lincoln University",
  "Fisk University",
  "Dillard University",

  // Liberal Arts Colleges
  "Williams College",
  "Amherst College",
  "Swarthmore College",
  "Wellesley College",
  "Pomona College",
  "Bowdoin College",
  "Claremont McKenna College",
  "Middlebury College",
  "Carleton College",
  "Haverford College",
  "Colby College",
  "Hamilton College",
  "Harvey Mudd College",
  "Wesleyan University",
  "Grinnell College",
  "Davidson College",
  "Colgate University",
  "Bates College",
  "Oberlin College",
  "Macalester College",
  "Vassar College",
  "Barnard College",
  "Bryn Mawr College",
  "Mount Holyoke College",
  "Smith College",
  "Reed College",
  "Whitman College",
  "Colorado College",
  "Kenyon College",
  "Bucknell University",
  "Lafayette College",
  "Trinity College",
  "Connecticut College",
  "Union College",
  "Furman University",
  "Rhodes College",
  "Sewanee: University of the South",
  "DePauw University",
  "Denison University",
  "College of the Holy Cross",

  // Community College Systems (by state)
  "Community College (Generic)",

  // Other Notable Schools
  "University of Notre Dame",
  "Fordham University",
  "Loyola University Chicago",
  "Loyola Marymount University",
  "Marquette University",
  "DePaul University",
  "Seton Hall University",
  "Creighton University",
  "University of San Diego",
  "University of San Francisco",
  "Saint Louis University",
  "Xavier University",
  "University of Dayton",
  "University of Scranton",
  "Fairfield University",
  "Providence College",
  "Quinnipiac University",
  "Sacred Heart University",
  "Elon University",
  "High Point University",
  "Rollins College",
  "Stetson University",
  "Chapman University",
  "University of the Pacific",
  "University of Tulsa",
  "University of Richmond",
  "Wake Forest University",
  "Belmont University",
  "Lipscomb University",
  "Samford University",
  "Mercer University",
  "Wofford College",
  "Ithaca College",
  "Marist College",
  "Siena College",
  "Bentley University",
  "Babson College",
  "Stonehill College",
  "Assumption University",
  "Hofstra University",
  "Adelphi University",
  "LIU Post",
  "Pace University",
  "The New School",
  "Pratt Institute",
  "Parsons School of Design",
  "School of Visual Arts",
  "Fashion Institute of Technology",
  "Rhode Island School of Design",
  "Savannah College of Art and Design",
  "Art Center College of Design",
  "Otis College of Art and Design",

  // Military Academies
  "United States Military Academy (West Point)",
  "United States Naval Academy",
  "United States Air Force Academy",
  "United States Coast Guard Academy",
  "United States Merchant Marine Academy",

  // Canadian Universities (for border students)
  "University of Toronto",
  "McGill University",
  "University of British Columbia",
  "University of Waterloo",
  "University of Alberta",
  "University of Calgary",
  "Queen's University",
  "Western University",
  "McMaster University",
  "University of Ottawa",
  "Dalhousie University",
  "University of Manitoba",
  "University of Saskatchewan",
  "Simon Fraser University",
  "York University",
  "Ryerson University",
  "Carleton University",

  // UK Universities
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London",
  "London School of Economics",
  "University of Edinburgh",
  "University of Manchester",
  "University of Bristol",
  "University of Warwick",
  "King's College London"
];

// Common course code prefixes organized by department
const COURSE_DEPARTMENTS = {
  "Accounting": ["ACCT", "ACC"],
  "Aerospace Engineering": ["AERO", "AE"],
  "African American Studies": ["AFAM", "AAS", "AFST"],
  "Anthropology": ["ANTH", "ANT"],
  "Arabic": ["ARAB"],
  "Architecture": ["ARCH"],
  "Art": ["ART", "ARTS"],
  "Art History": ["ARTH", "ARH"],
  "Astronomy": ["ASTR", "AST"],
  "Biochemistry": ["BCHM", "BIOC", "BCH"],
  "Bioengineering": ["BIOE", "BE", "BIEN"],
  "Biology": ["BIO", "BIOL"],
  "Biomedical Engineering": ["BME", "BMEN"],
  "Business": ["BUS", "BUSI", "BUSN"],
  "Business Administration": ["BA", "BADM"],
  "Chemical Engineering": ["CHE", "CHME", "CHEN"],
  "Chemistry": ["CHEM", "CHM"],
  "Chinese": ["CHIN", "CHN"],
  "Civil Engineering": ["CE", "CIVE", "CVEN"],
  "Classics": ["CLSS", "CLAS", "CL"],
  "Communication": ["COMM", "COM"],
  "Computer Engineering": ["CMPE", "CPE"],
  "Computer Science": ["CS", "CSC", "CSCI", "CIS", "COMP", "CPSC"],
  "Criminal Justice": ["CJ", "CRIM", "CRJU"],
  "Dance": ["DANC", "DAN"],
  "Data Science": ["DS", "DATA"],
  "Earth Science": ["ERTH", "ESCI", "GEOS"],
  "Economics": ["ECON", "ECO", "EC"],
  "Education": ["EDUC", "ED", "EDU"],
  "Electrical Engineering": ["EE", "ECE", "EECE", "ELEC"],
  "English": ["ENGL", "ENG", "EN"],
  "Environmental Science": ["ENVS", "ENV", "ENVI"],
  "Environmental Engineering": ["ENVE", "EVEN"],
  "Ethnic Studies": ["ETHN", "ES"],
  "Film Studies": ["FILM", "CINE"],
  "Finance": ["FIN", "FINA"],
  "Food Science": ["FDSC", "FSC"],
  "French": ["FREN", "FR"],
  "Gender Studies": ["GNDR", "WMST", "WGS"],
  "Genetics": ["GEN", "GENE"],
  "Geography": ["GEOG", "GEO"],
  "Geology": ["GEOL", "GLY"],
  "German": ["GERM", "GER"],
  "Graphic Design": ["GRPH", "GD"],
  "Health Sciences": ["HLTH", "HSC", "HSCI"],
  "History": ["HIST", "HIS", "HST"],
  "Hospitality Management": ["HOSP", "HTM"],
  "Human Development": ["HDEV", "HD"],
  "Industrial Engineering": ["IE", "ISE", "INEN"],
  "Information Systems": ["IS", "INFS", "MIS"],
  "Information Technology": ["IT", "INFT"],
  "International Relations": ["IR", "INTL"],
  "Italian": ["ITAL", "IT"],
  "Japanese": ["JAPN", "JPN"],
  "Journalism": ["JOUR", "JRN"],
  "Kinesiology": ["KINE", "KIN", "KNES"],
  "Korean": ["KOR", "KORN"],
  "Latin": ["LATN", "LAT"],
  "Law": ["LAW", "LAWS"],
  "Linguistics": ["LING", "LIN"],
  "Management": ["MGMT", "MGT", "MAN"],
  "Marketing": ["MKTG", "MKT", "MRKT"],
  "Materials Science": ["MSE", "MATE", "MATL"],
  "Mathematics": ["MATH", "MTH", "MA"],
  "Mechanical Engineering": ["ME", "MECH", "MEEN"],
  "Media Studies": ["MDIA", "MDST"],
  "Microbiology": ["MICR", "MICRO", "MCB"],
  "Military Science": ["MILS", "MS"],
  "Molecular Biology": ["MOLB", "MB"],
  "Music": ["MUS", "MUSC", "MUSI"],
  "Neuroscience": ["NEUR", "NSCI", "NEU"],
  "Nuclear Engineering": ["NE", "NUCL", "NUEN"],
  "Nursing": ["NURS", "NUR", "NSG"],
  "Nutrition": ["NUTR", "NTR"],
  "Oceanography": ["OCNG", "OCN", "OCEA"],
  "Operations Management": ["OPMT", "OM"],
  "Petroleum Engineering": ["PETE", "PGE"],
  "Pharmacology": ["PHAR", "PHCL"],
  "Philosophy": ["PHIL", "PHL"],
  "Physics": ["PHYS", "PHY", "PH"],
  "Political Science": ["POLS", "POLI", "PS", "PLSC", "POL"],
  "Portuguese": ["PORT", "POR"],
  "Psychology": ["PSYC", "PSY", "PSYCH"],
  "Public Health": ["PUBH", "PH", "HLTH"],
  "Public Policy": ["PUBP", "PP"],
  "Real Estate": ["RE", "REAL"],
  "Religious Studies": ["RELS", "REL", "RELI"],
  "Russian": ["RUSS", "RUS"],
  "Social Work": ["SOCW", "SW", "SOWK"],
  "Sociology": ["SOC", "SOCI"],
  "Spanish": ["SPAN", "SPN", "SP"],
  "Special Education": ["SPED", "SPE"],
  "Speech Pathology": ["SPCH", "SLP", "CSD"],
  "Statistics": ["STAT", "STA", "STATS"],
  "Supply Chain Management": ["SCM", "SCMT"],
  "Theater": ["THTR", "THE", "THEA", "DRAM"],
  "Urban Planning": ["URPL", "UP"],
  "Veterinary Science": ["VET", "VTSC"],
  "Writing": ["WRIT", "WR"]
};

// Generate full course codes (prefix + common numbers)
const COURSE_NUMBERS = ["101", "102", "110", "111", "112", "120", "150", "200", "201", "202", "210", "211", "220", "230", "250", "300", "301", "302", "310", "311", "320", "330", "340", "350", "400", "401", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "501", "510", "520", "530", "540", "550", "600", "601", "610", "620"];

// Build a flat list of course codes for autocomplete
function generateCourseCodes() {
  const codes = [];
  for (const [dept, prefixes] of Object.entries(COURSE_DEPARTMENTS)) {
    // Use the first (most common) prefix for each department
    const prefix = prefixes[0];
    COURSE_NUMBERS.forEach(num => {
      codes.push(`${prefix} ${num}`);
    });
    // Also add alternate prefixes with just common numbers
    prefixes.slice(1).forEach(altPrefix => {
      ["101", "102", "201", "202", "301", "302", "401"].forEach(num => {
        codes.push(`${altPrefix} ${num}`);
      });
    });
  }
  return codes;
}

// Get just the department prefixes for quick display
function getDepartmentPrefixes() {
  const prefixes = [];
  for (const [dept, codes] of Object.entries(COURSE_DEPARTMENTS)) {
    codes.forEach(code => {
      prefixes.push({ code, department: dept });
    });
  }
  return prefixes;
}

// Search/filter universities by query
function searchUniversities(query) {
  if (!query) return UNIVERSITIES;
  const lower = query.toLowerCase();
  return UNIVERSITIES.filter(u => u.toLowerCase().includes(lower));
}

// Search/filter course codes by query
function searchCourseCodes(query) {
  if (!query) return Object.keys(COURSE_DEPARTMENTS);
  const lower = query.toLowerCase();
  const results = [];

  for (const [dept, prefixes] of Object.entries(COURSE_DEPARTMENTS)) {
    if (dept.toLowerCase().includes(lower) || prefixes.some(p => p.toLowerCase().startsWith(lower.split(' ')[0]))) {
      // If they typed a number too, filter to matching numbers
      const parts = query.trim().split(/\s+/);
      if (parts.length > 1) {
        const numQuery = parts[1];
        const prefix = prefixes.find(p => p.toLowerCase() === parts[0].toLowerCase()) || prefixes[0];
        COURSE_NUMBERS.filter(n => n.startsWith(numQuery)).forEach(num => {
          results.push(`${prefix} ${num}`);
        });
      } else {
        // Just show department prefixes with common numbers
        const prefix = prefixes[0];
        ["101", "201", "301", "401"].forEach(num => {
          results.push(`${prefix} ${num}`);
        });
      }
    }
  }
  return results;
}
