// Comprehensive US University and Course Code Database
// Used by upload.html and browse.html for autocomplete/filtering

const UNIVERSITIES = [
  // Ivy League
  "Harvard University",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Pennsylvania",
  "Brown University",
  "Dartmouth College",
  "Cornell University",

  // Big Ten
  "University of Michigan",
  "Michigan State University",
  "Ohio State University",
  "Penn State University",
  "University of Wisconsin-Madison",
  "University of Minnesota",
  "University of Iowa",
  "University of Illinois Urbana-Champaign",
  "Northwestern University",
  "Purdue University",
  "Indiana University Bloomington",
  "University of Nebraska-Lincoln",
  "University of Maryland",
  "Rutgers University",
  "University of Oregon",
  "University of Washington",
  "UCLA",
  "USC",

  // SEC
  "University of Alabama",
  "Auburn University",
  "University of Florida",
  "University of Georgia",
  "Louisiana State University",
  "University of Tennessee",
  "University of Kentucky",
  "University of South Carolina",
  "University of Mississippi",
  "Mississippi State University",
  "University of Arkansas",
  "Vanderbilt University",
  "University of Missouri",
  "Texas A&M University",
  "University of Texas at Austin",
  "University of Oklahoma",

  // ACC
  "Duke University",
  "University of North Carolina at Chapel Hill",
  "NC State University",
  "Wake Forest University",
  "University of Virginia",
  "Virginia Tech",
  "Georgia Tech",
  "Florida State University",
  "University of Miami",
  "Clemson University",
  "Boston College",
  "Syracuse University",
  "University of Pittsburgh",
  "University of Louisville",
  "Stanford University",
  "University of California, Berkeley",
  "Southern Methodist University",

  // Big 12
  "Baylor University",
  "Texas Christian University",
  "Texas Tech University",
  "University of Kansas",
  "Kansas State University",
  "Iowa State University",
  "Oklahoma State University",
  "West Virginia University",
  "University of Cincinnati",
  "University of Houston",
  "Brigham Young University",
  "University of Central Florida",
  "University of Colorado Boulder",
  "Arizona State University",
  "University of Arizona",
  "University of Utah",

  // Pac-12 / West Coast
  "University of Southern California",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of California, Davis",
  "University of California, Santa Barbara",
  "University of California, Irvine",
  "University of California, Santa Cruz",
  "University of California, Riverside",
  "University of California, Merced",
  "California Polytechnic State University",
  "San Diego State University",
  "San Jose State University",
  "California State University, Fullerton",
  "California State University, Long Beach",
  "California State University, Northridge",
  "California State University, Sacramento",
  "California State University, Los Angeles",
  "California State University, Fresno",
  "California State University, San Bernardino",
  "San Francisco State University",
  "Oregon State University",
  "Washington State University",
  "University of Nevada, Las Vegas",
  "University of Nevada, Reno",
  "University of Hawaii at Manoa",
  "Boise State University",

  // Top Private Universities
  "Massachusetts Institute of Technology",
  "California Institute of Technology",
  "Carnegie Mellon University",
  "Johns Hopkins University",
  "Rice University",
  "Emory University",
  "Georgetown University",
  "New York University",
  "University of Chicago",
  "Washington University in St. Louis",
  "Tufts University",
  "Brandeis University",
  "Case Western Reserve University",
  "University of Rochester",
  "Lehigh University",
  "Villanova University",
  "Santa Clara University",
  "Pepperdine University",
  "Gonzaga University",
  "Tulane University",
  "Northeastern University",
  "Boston University",
  "George Washington University",
  "American University",
  "Drexel University",
  "Stevens Institute of Technology",
  "Rensselaer Polytechnic Institute",
  "Worcester Polytechnic Institute",
  "Rose-Hulman Institute of Technology",

  // Major State Universities
  "University of Connecticut",
  "University of Massachusetts Amherst",
  "University of Vermont",
  "University of New Hampshire",
  "University of Maine",
  "University of Rhode Island",
  "University of Delaware",
  "Stony Brook University",
  "University at Buffalo",
  "University at Albany",
  "Binghamton University",
  "Temple University",
  "University of North Carolina at Charlotte",
  "University of North Carolina at Greensboro",
  "East Carolina University",
  "Appalachian State University",
  "College of William & Mary",
  "James Madison University",
  "George Mason University",
  "Old Dominion University",
  "Virginia Commonwealth University",
  "University of South Florida",
  "Florida International University",
  "Florida Atlantic University",
  "University of North Florida",
  "Georgia State University",
  "Kennesaw State University",
  "University of Alabama at Birmingham",
  "University of Alabama in Huntsville",
  "Middle Tennessee State University",
  "University of Memphis",
  "University of Louisville",
  "Western Kentucky University",
  "Northern Kentucky University",
  "University of Dayton",
  "Miami University (Ohio)",
  "Ohio University",
  "Bowling Green State University",
  "Kent State University",
  "University of Akron",
  "Wright State University",
  "Ball State University",
  "Indiana University-Purdue University Indianapolis",
  "University of Wisconsin-Milwaukee",
  "University of Wisconsin-Green Bay",
  "Marquette University",
  "University of Northern Iowa",
  "Drake University",
  "Creighton University",
  "University of South Dakota",
  "North Dakota State University",
  "University of North Dakota",
  "Montana State University",
  "University of Montana",
  "University of Wyoming",
  "Colorado State University",
  "University of Denver",
  "University of Colorado Denver",
  "University of Colorado Colorado Springs",
  "New Mexico State University",
  "University of New Mexico",
  "Northern Arizona University",
  "University of Idaho",
  "Portland State University",
  "University of Portland",
  "Western Washington University",
  "Eastern Washington University",
  "Central Washington University",
  "University of Alaska Anchorage",

  // Texas Schools
  "University of Texas at Dallas",
  "University of Texas at San Antonio",
  "University of Texas at Arlington",
  "University of Texas at El Paso",
  "University of North Texas",
  "Texas State University",
  "Sam Houston State University",
  "Lamar University",
  "Stephen F. Austin State University",
  "Prairie View A&M University",

  // HBCUs
  "Howard University",
  "Spelman College",
  "Morehouse College",
  "Hampton University",
  "Tuskegee University",
  "Florida A&M University",
  "North Carolina A&T State University",
  "Morgan State University",
  "Clark Atlanta University",
  "Xavier University of Louisiana",
  "Tennessee State University",
  "Jackson State University",
  "Southern University",
  "Grambling State University",
  "Alabama A&M University",
  "Alabama State University",
  "Delaware State University",
  "Bowie State University",
  "Coppin State University",
  "Norfolk State University",
  "Virginia State University",
  "South Carolina State University",
  "Bethune-Cookman University",
  "Lincoln University",
  "Fisk University",
  "Dillard University",

  // Liberal Arts Colleges
  "Williams College",
  "Amherst College",
  "Swarthmore College",
  "Wellesley College",
  "Pomona College",
  "Bowdoin College",
  "Claremont McKenna College",
  "Middlebury College",
  "Carleton College",
  "Haverford College",
  "Colby College",
  "Hamilton College",
  "Harvey Mudd College",
  "Wesleyan University",
  "Grinnell College",
  "Davidson College",
  "Colgate University",
  "Bates College",
  "Oberlin College",
  "Macalester College",
  "Vassar College",
  "Barnard College",
  "Bryn Mawr College",
  "Mount Holyoke College",
  "Smith College",
  "Reed College",
  "Whitman College",
  "Colorado College",
  "Kenyon College",
  "Bucknell University",
  "Lafayette College",
  "Trinity College",
  "Connecticut College",
  "Union College",
  "Furman University",
  "Rhodes College",
  "Sewanee: University of the South",
  "DePauw University",
  "Denison University",
  "College of the Holy Cross",

  // Community Colleges - Missouri
  "Ozarks Technical Community College (OTC)",
  "Metropolitan Community College - Kansas City",
  "St. Louis Community College",
  "State Fair Community College",
  "Crowder College",
  "East Central College",
  "Jefferson College",
  "Mineral Area College",
  "Moberly Area Community College",
  "North Central Missouri College",
  "Ozarks Technical Community College - Richwood Valley",
  "Ozarks Technical Community College - Table Rock",
  "St. Charles Community College",
  "Three Rivers College",

  // Community Colleges - California
  "Santa Monica College",
  "Pasadena City College",
  "De Anza College",
  "Foothill College",
  "Diablo Valley College",
  "Mt. San Antonio College",
  "Orange Coast College",
  "El Camino College",
  "Glendale Community College",
  "Long Beach City College",
  "City College of San Francisco",
  "Sacramento City College",
  "San Diego Mesa College",
  "Palomar College",
  "Riverside City College",
  "Bakersfield College",
  "Fresno City College",
  "Santa Rosa Junior College",
  "College of the Canyons",
  "Moorpark College",
  "Irvine Valley College",
  "Saddleback College",
  "Cypress College",
  "Fullerton College",
  "Golden West College",
  "Cerritos College",
  "Citrus College",
  "Cuesta College",
  "College of the Desert",
  "College of Marin",
  "Chabot College",
  "Los Angeles City College",
  "Los Angeles Valley College",
  "West Los Angeles College",
  "Los Angeles Pierce College",
  "Los Angeles Trade-Technical College",
  "East Los Angeles College",

  // Community Colleges - Texas
  "Austin Community College",
  "Houston Community College",
  "Dallas College",
  "Tarrant County College",
  "San Antonio College",
  "Lone Star College",
  "Collin College",
  "El Paso Community College",
  "Blinn College",
  "Tyler Junior College",
  "Kilgore College",
  "Amarillo College",
  "McLennan Community College",
  "Temple College",
  "Midland College",
  "Odessa College",
  "South Plains College",
  "Laredo College",
  "Del Mar College",
  "Brazosport College",
  "Galveston College",
  "Hill College",
  "Weatherford College",
  "Navarro College",
  "Paris Junior College",
  "Northeast Texas Community College",
  "Texarkana College",
  "Trinity Valley Community College",

  // Community Colleges - Florida
  "Miami Dade College",
  "Broward College",
  "Valencia College",
  "Seminole State College of Florida",
  "Palm Beach State College",
  "Hillsborough Community College",
  "Santa Fe College",
  "St. Petersburg College",
  "Tallahassee Community College",
  "Indian River State College",
  "Daytona State College",
  "Eastern Florida State College",
  "State College of Florida",
  "Pensacola State College",
  "College of Central Florida",
  "Northwest Florida State College",
  "Gulf Coast State College",
  "Polk State College",

  // Community Colleges - New York
  "Borough of Manhattan Community College",
  "LaGuardia Community College",
  "Queensborough Community College",
  "Kingsborough Community College",
  "Bronx Community College",
  "Nassau Community College",
  "Suffolk County Community College",
  "Westchester Community College",
  "Monroe Community College",
  "Onondaga Community College",
  "Erie Community College",
  "Dutchess Community College",
  "Rockland Community College",
  "Orange County Community College",
  "Hudson Valley Community College",
  "Mohawk Valley Community College",
  "Tompkins Cortland Community College",
  "Finger Lakes Community College",
  "Corning Community College",

  // Community Colleges - Illinois
  "College of DuPage",
  "Harper College",
  "Moraine Valley Community College",
  "Oakton Community College",
  "Elgin Community College",
  "College of Lake County",
  "Joliet Junior College",
  "Prairie State College",
  "South Suburban College",
  "Triton College",
  "Waubonsee Community College",
  "McHenry County College",
  "Rock Valley College",
  "Heartland Community College",
  "Illinois Central College",
  "Parkland College",
  "John A. Logan College",

  // Community Colleges - Ohio
  "Columbus State Community College",
  "Cuyahoga Community College",
  "Cincinnati State Technical and Community College",
  "Sinclair Community College",
  "Lakeland Community College",
  "Lorain County Community College",
  "Stark State College",
  "Owens Community College",
  "Clark State College",
  "Terra State Community College",

  // Community Colleges - Pennsylvania
  "Community College of Philadelphia",
  "Community College of Allegheny County",
  "Montgomery County Community College",
  "Bucks County Community College",
  "Delaware County Community College",
  "Northampton Community College",
  "Lehigh Carbon Community College",
  "Harrisburg Area Community College",
  "Luzerne County Community College",
  "Butler County Community College",

  // Community Colleges - Michigan
  "Grand Rapids Community College",
  "Lansing Community College",
  "Henry Ford College",
  "Macomb Community College",
  "Oakland Community College",
  "Washtenaw Community College",
  "Schoolcraft College",
  "Mott Community College",
  "Kalamazoo Valley Community College",
  "Delta College",
  "Northwestern Michigan College",

  // Community Colleges - North Carolina
  "Wake Technical Community College",
  "Central Piedmont Community College",
  "Guilford Technical Community College",
  "Durham Technical Community College",
  "Fayetteville Technical Community College",
  "Forsyth Technical Community College",
  "Cape Fear Community College",
  "Pitt Community College",
  "Catawba Valley Community College",
  "Asheville-Buncombe Technical Community College",
  "Rowan-Cabarrus Community College",
  "Mitchell Community College",

  // Community Colleges - Virginia
  "Northern Virginia Community College",
  "Tidewater Community College",
  "J. Sargeant Reynolds Community College",
  "Thomas Nelson Community College",
  "Piedmont Virginia Community College",
  "Blue Ridge Community College",
  "Central Virginia Community College",
  "New River Community College",
  "Lord Fairfax Community College",

  // Community Colleges - Georgia
  "Georgia State University - Perimeter College",
  "Atlanta Technical College",
  "Chattahoochee Technical College",
  "Georgia Piedmont Technical College",
  "Gwinnett Technical College",
  "Savannah Technical College",
  "Albany Technical College",
  "Augusta Technical College",

  // Community Colleges - Washington
  "Bellevue College",
  "Green River College",
  "Highline College",
  "South Puget Sound Community College",
  "Tacoma Community College",
  "Spokane Community College",
  "Clark College",
  "Whatcom Community College",
  "Skagit Valley College",
  "Olympic College",
  "Pierce College",
  "Edmonds College",
  "Shoreline Community College",
  "Seattle Central College",
  "North Seattle College",
  "South Seattle College",

  // Community Colleges - Oregon
  "Portland Community College",
  "Chemeketa Community College",
  "Lane Community College",
  "Mt. Hood Community College",
  "Clackamas Community College",
  "Linn-Benton Community College",
  "Rogue Community College",
  "Umpqua Community College",
  "Central Oregon Community College",

  // Community Colleges - Arizona
  "Maricopa Community Colleges",
  "Mesa Community College",
  "Scottsdale Community College",
  "Glendale Community College (AZ)",
  "Phoenix College",
  "Chandler-Gilbert Community College",
  "South Mountain Community College",
  "Paradise Valley Community College",
  "Gateway Community College (AZ)",
  "Pima Community College",
  "Yavapai College",
  "Coconino Community College",
  "Mohave Community College",

  // Community Colleges - Colorado
  "Community College of Denver",
  "Community College of Aurora",
  "Arapahoe Community College",
  "Front Range Community College",
  "Red Rocks Community College",
  "Pikes Peak State College",
  "Pueblo Community College",
  "Aims Community College",
  "Colorado Mountain College",
  "Otero College",

  // Community Colleges - New Jersey
  "Bergen Community College",
  "Middlesex College",
  "Brookdale Community College",
  "County College of Morris",
  "Passaic County Community College",
  "Raritan Valley Community College",
  "Ocean County College",
  "Mercer County Community College",
  "Camden County College",
  "Union County College",
  "Hudson County Community College",
  "Essex County College",
  "Rowan College of South Jersey",

  // Community Colleges - Massachusetts
  "Bunker Hill Community College",
  "Middlesex Community College",
  "Northern Essex Community College",
  "Massasoit Community College",
  "Quinsigamond Community College",
  "Springfield Technical Community College",
  "Holyoke Community College",
  "Cape Cod Community College",
  "Bristol Community College",
  "Berkshire Community College",

  // Community Colleges - Connecticut
  "Housatonic Community College",
  "Norwalk Community College",
  "Manchester Community College",
  "Capital Community College",
  "Gateway Community College (CT)",
  "Naugatuck Valley Community College",
  "Middlesex Community College (CT)",
  "Three Rivers Community College (CT)",

  // Community Colleges - Tennessee
  "Nashville State Community College",
  "Pellissippi State Community College",
  "Chattanooga State Community College",
  "Southwest Tennessee Community College",
  "Volunteer State Community College",
  "Roane State Community College",
  "Columbia State Community College",
  "Walters State Community College",
  "Motlow State Community College",
  "Northeast State Community College",
  "Dyersburg State Community College",
  "Jackson State Community College",

  // Community Colleges - Alabama
  "Jefferson State Community College",
  "Shelton State Community College",
  "Calhoun Community College",
  "Wallace State Community College",
  "Coastal Alabama Community College",
  "Gadsden State Community College",
  "Lawson State Community College",
  "Central Alabama Community College",
  "Snead State Community College",
  "Bishop State Community College",

  // Community Colleges - Kentucky
  "Bluegrass Community and Technical College",
  "Jefferson Community and Technical College",
  "Owensboro Community and Technical College",
  "Elizabethtown Community and Technical College",
  "Ashland Community and Technical College",
  "Somerset Community College",
  "Hopkinsville Community College",
  "Madisonville Community College",

  // Community Colleges - Indiana
  "Ivy Tech Community College",
  "Vincennes University",

  // Community Colleges - Wisconsin
  "Milwaukee Area Technical College",
  "Madison Area Technical College",
  "Fox Valley Technical College",
  "Gateway Technical College",
  "Waukesha County Technical College",
  "Northeast Wisconsin Technical College",
  "Chippewa Valley Technical College",
  "Western Technical College",

  // Community Colleges - Minnesota
  "Minneapolis Community and Technical College",
  "Hennepin Technical College",
  "Anoka-Ramsey Community College",
  "Century College",
  "Normandale Community College",
  "North Hennepin Community College",
  "Inver Hills Community College",
  "Rochester Community and Technical College",
  "St. Cloud Technical and Community College",
  "Dakota County Technical College",

  // Community Colleges - Iowa
  "Des Moines Area Community College",
  "Kirkwood Community College",
  "Iowa Western Community College",
  "Hawkeye Community College",
  "Eastern Iowa Community Colleges",
  "Indian Hills Community College",
  "Northeast Iowa Community College",
  "Northwest Iowa Community College",
  "Southwestern Community College",
  "Southeastern Community College",

  // Community Colleges - Kansas
  "Johnson County Community College",
  "Butler Community College",
  "Hutchinson Community College",
  "Barton County Community College",
  "Dodge City Community College",
  "Garden City Community College",
  "Cowley County Community College",
  "Cloud County Community College",
  "Coffeyville Community College",
  "Colby Community College",

  // Community Colleges - Oklahoma
  "Tulsa Community College",
  "Oklahoma City Community College",
  "Rose State College",
  "Redlands Community College",
  "Seminole State College",
  "Northern Oklahoma College",
  "Eastern Oklahoma State College",
  "Northeastern Oklahoma A&M College",
  "Connors State College",
  "Carl Albert State College",
  "Murray State College",
  "Western Oklahoma State College",

  // Community Colleges - Arkansas
  "NorthWest Arkansas Community College",
  "Pulaski Technical College",
  "National Park College",
  "North Arkansas College",
  "South Arkansas Community College",
  "Arkansas State University - Mid-South",
  "University of Arkansas Community College at Batesville",
  "University of Arkansas Community College at Morrilton",
  "East Arkansas Community College",
  "College of the Ouachitas",
  "Ozarka College",
  "Black River Technical College",
  "Cossatot Community College",
  "Phillips Community College",
  "Southeast Arkansas College",
  "Arkansas Northeastern College",
  "Rich Mountain Community College",

  // Community Colleges - Mississippi
  "Hinds Community College",
  "Jones County Junior College",
  "Pearl River Community College",
  "Itawamba Community College",
  "Northwest Mississippi Community College",
  "Northeast Mississippi Community College",
  "Mississippi Gulf Coast Community College",
  "East Mississippi Community College",
  "Meridian Community College",
  "Copiah-Lincoln Community College",
  "Holmes Community College",
  "Southwest Mississippi Community College",
  "Coahoma Community College",
  "East Central Community College",
  "Mississippi Delta Community College",

  // Community Colleges - Louisiana
  "Baton Rouge Community College",
  "Delgado Community College",
  "Bossier Parish Community College",
  "South Louisiana Community College",
  "Nunez Community College",
  "SOWELA Technical Community College",
  "River Parishes Community College",
  "Central Louisiana Technical Community College",
  "Fletcher Technical Community College",
  "Northshore Technical Community College",

  // Community Colleges - South Carolina
  "Greenville Technical College",
  "Trident Technical College",
  "Midlands Technical College",
  "Spartanburg Community College",
  "Horry-Georgetown Technical College",
  "Tri-County Technical College",
  "Florence-Darlington Technical College",
  "York Technical College",
  "Piedmont Technical College",
  "Central Carolina Technical College",

  // Community Colleges - Maryland
  "Montgomery College",
  "Community College of Baltimore County",
  "Anne Arundel Community College",
  "Prince George's Community College",
  "Howard Community College",
  "Frederick Community College",
  "Harford Community College",
  "College of Southern Maryland",
  "Carroll Community College",
  "Chesapeake College",
  "Cecil College",

  // Community Colleges - Nevada
  "College of Southern Nevada",
  "Truckee Meadows Community College",
  "Western Nevada College",
  "Great Basin College",

  // Community Colleges - New Mexico
  "Central New Mexico Community College",
  "San Juan College",
  "Santa Fe Community College",
  "Dona Ana Community College",
  "Clovis Community College",
  "Eastern New Mexico University - Roswell",

  // Community Colleges - Idaho
  "College of Western Idaho",
  "College of Southern Idaho",
  "College of Eastern Idaho",
  "North Idaho College",

  // Community Colleges - Montana
  "Flathead Valley Community College",
  "Helena College",
  "Miles Community College",
  "Dawson Community College",

  // Community Colleges - Wyoming
  "Casper College",
  "Laramie County Community College",
  "Central Wyoming College",
  "Northwest College",
  "Western Wyoming Community College",
  "Sheridan College",
  "Eastern Wyoming College",

  // Community Colleges - Utah
  "Salt Lake Community College",
  "Snow College",
  "Utah State University Eastern",

  // Community Colleges - Nebraska
  "Metropolitan Community College (NE)",
  "Southeast Community College",
  "Central Community College",
  "Northeast Community College",
  "Mid-Plains Community College",
  "Western Nebraska Community College",

  // Community Colleges - South Dakota
  "Southeast Technical College",
  "Lake Area Technical College",
  "Mitchell Technical College",
  "Western Dakota Technical College",

  // Community Colleges - North Dakota
  "Bismarck State College",
  "North Dakota State College of Science",
  "Lake Region State College",
  "Williston State College",

  // Community Colleges - Hawaii
  "Kapiolani Community College",
  "Honolulu Community College",
  "Leeward Community College",
  "Windward Community College",

  // Community Colleges - Alaska
  "University of Alaska Anchorage - Community Campuses",
  "University of Alaska Southeast",

  // Community Colleges - Maine
  "Southern Maine Community College",
  "Central Maine Community College",
  "Eastern Maine Community College",
  "Northern Maine Community College",
  "Kennebec Valley Community College",
  "York County Community College",
  "Washington County Community College",

  // Community Colleges - Vermont
  "Community College of Vermont",

  // Community Colleges - New Hampshire
  "NHTI - Concord's Community College",
  "Manchester Community College (NH)",
  "Nashua Community College",
  "Great Bay Community College",
  "Lakes Region Community College",
  "River Valley Community College",
  "White Mountains Community College",

  // Community Colleges - Rhode Island
  "Community College of Rhode Island",

  // Community Colleges - Delaware
  "Delaware Technical Community College",

  // Community Colleges - West Virginia
  "Blue Ridge Community and Technical College (WV)",
  "BridgeValley Community and Technical College",
  "Mountwest Community and Technical College",
  "New River Community and Technical College (WV)",
  "Pierpont Community and Technical College",
  "Southern West Virginia Community and Technical College",

  // Additional State Universities & Regional Schools
  "Appalachian State University",
  "Murray State University",
  "Eastern Kentucky University",
  "Western Kentucky University",
  "Morehead State University",
  "Southeast Missouri State University",
  "Missouri State University",
  "Missouri University of Science and Technology",
  "University of Missouri - Kansas City",
  "University of Missouri - St. Louis",
  "Truman State University",
  "Northwest Missouri State University",
  "Central Missouri State University",
  "Lincoln University (MO)",
  "William Jewell College",
  "Drury University",
  "Evangel University",
  "Missouri Southern State University",
  "Missouri Western State University",
  "Pittsburg State University",
  "Emporia State University",
  "Fort Hays State University",
  "Wichita State University",
  "Washburn University",
  "University of Central Oklahoma",
  "University of Science and Arts of Oklahoma",
  "Northeastern State University",
  "Southeastern Oklahoma State University",
  "Northwestern Oklahoma State University",
  "Southwestern Oklahoma State University",
  "East Central University",
  "Cameron University",
  "Rogers State University",
  "Langston University",
  "University of Central Arkansas",
  "Arkansas State University",
  "Arkansas Tech University",
  "Henderson State University",
  "Harding University",
  "University of the Ozarks",
  "John Brown University",
  "Ouachita Baptist University",
  "Lyon College",
  "Hendrix College",
  "Southern Arkansas University",
  "University of Arkansas at Little Rock",
  "University of Arkansas at Pine Bluff",
  "University of Arkansas at Fort Smith",
  "University of Arkansas at Monticello",
  "Southeastern Louisiana University",
  "University of Louisiana at Lafayette",
  "University of Louisiana at Monroe",
  "Louisiana Tech University",
  "McNeese State University",
  "Nicholls State University",
  "Northwestern State University",
  "Loyola University New Orleans",
  "Tulane University",
  "University of Southern Mississippi",
  "Mississippi State University",
  "Alcorn State University",
  "Delta State University",
  "Mississippi University for Women",
  "Mississippi Valley State University",
  "William Carey University",
  "Millsaps College",
  "Belhaven University",
  "Blue Mountain College",
  "Tougaloo College",
  "Rust College",
  "University of West Alabama",
  "University of North Alabama",
  "University of South Alabama",
  "Troy University",
  "Jacksonville State University",
  "Samford University",
  "Birmingham-Southern College",
  "Spring Hill College",
  "Stillman College",
  "Miles College",
  "Talladega College",
  "Oakwood University",
  "University of Montevallo",
  "Athens State University",
  "University of West Florida",
  "University of North Georgia",
  "Georgia Southern University",
  "Valdosta State University",
  "Columbus State University",
  "Albany State University",
  "Fort Valley State University",
  "Savannah State University",
  "Armstrong State University",
  "Georgia College & State University",
  "Berry College",
  "Oglethorpe University",
  "Agnes Scott College",
  "Spelman College",
  "Covenant College",
  "Reinhardt University",
  "Piedmont University",
  "LaGrange College",
  "Shorter University",
  "Toccoa Falls College",
  "University of North Carolina at Wilmington",
  "University of North Carolina at Asheville",
  "University of North Carolina at Pembroke",
  "Western Carolina University",
  "Winston-Salem State University",
  "Fayetteville State University",
  "Elizabeth City State University",
  "North Carolina Central University",
  "Campbell University",
  "Elon University",
  "High Point University",
  "Guilford College",
  "Meredith College",
  "Salem College",
  "Queens University of Charlotte",
  "Belmont Abbey College",
  "Barton College",
  "Catawba College",
  "Chowan University",
  "Gardner-Webb University",
  "Lenoir-Rhyne University",
  "Lees-McRae College",
  "Mars Hill University",
  "Methodist University",
  "Pfeiffer University",
  "Wingate University",
  "Coastal Carolina University",
  "The Citadel",
  "Charleston Southern University",
  "Anderson University (SC)",
  "Bob Jones University",
  "Converse University",
  "Erskine College",
  "Francis Marion University",
  "Lander University",
  "Limestone University",
  "Newberry College",
  "Presbyterian College",
  "Southern Wesleyan University",
  "Winthrop University",
  "Wofford College",
  "Radford University",
  "Longwood University",
  "Christopher Newport University",
  "Mary Baldwin University",
  "Randolph-Macon College",
  "Hampden-Sydney College",
  "Washington and Lee University",
  "Sweet Briar College",
  "Hollins University",
  "Roanoke College",
  "Lynchburg University",
  "Shenandoah University",
  "Averett University",
  "Bridgewater College",
  "Eastern Mennonite University",
  "Emory & Henry College",
  "Ferrum College",
  "Virginia Wesleyan University",
  "University of Mary Washington",
  "Shepherd University",
  "West Liberty University",
  "Fairmont State University",
  "Concord University",
  "Glenville State University",
  "Alderson Broaddus University",
  "Bethany College (WV)",
  "Davis & Elkins College",
  "West Virginia Wesleyan College",
  "Wheeling University",
  "Marshall University",
  "Frostburg State University",
  "Salisbury University",
  "Towson University",
  "University of Maryland, Baltimore County",
  "Coppin State University",
  "St. Mary's College of Maryland",
  "Washington College",
  "Goucher College",
  "Hood College",
  "Loyola University Maryland",
  "McDaniel College",
  "Mount St. Mary's University",
  "Stevenson University",
  "University of Baltimore",
  "University of Delaware",
  "Delaware State University",
  "Wesley College",
  "Goldey-Beacom College",
  "Wilmington University",
  "Rider University",
  "Monmouth University",
  "Rowan University",
  "The College of New Jersey",
  "New Jersey Institute of Technology",
  "Montclair State University",
  "William Paterson University",
  "Kean University",
  "Ramapo College",
  "Stockton University",
  "Caldwell University",
  "Georgian Court University",
  "Felician University",
  "Saint Peter's University",
  "Fairleigh Dickinson University",
  "Drew University",
  "SUNY Cortland",
  "SUNY Geneseo",
  "SUNY Oswego",
  "SUNY Plattsburgh",
  "SUNY Brockport",
  "SUNY Fredonia",
  "SUNY Oneonta",
  "SUNY Potsdam",
  "SUNY New Paltz",
  "SUNY Purchase",
  "SUNY Old Westbury",
  "SUNY Empire State College",
  "SUNY Maritime College",
  "SUNY College of Environmental Science and Forestry",
  "SUNY Polytechnic Institute",
  "St. John's University",
  "Manhattan College",
  "Le Moyne College",
  "Niagara University",
  "Canisius University",
  "St. Bonaventure University",
  "Hartwick College",
  "Hobart and William Smith Colleges",
  "Skidmore College",
  "Union College (NY)",
  "Rensselaer Polytechnic Institute",
  "Clarkson University",
  "Rochester Institute of Technology",
  "Alfred University",
  "Bard College",
  "Sarah Lawrence College",
  "Manhattanville College",
  "Wagner College",
  "College of Mount Saint Vincent",
  "Dominican University New York",
  "Keuka College",
  "Utica University",
  "Roberts Wesleyan University",
  "Daemen University",
  "Medaille University",
  "Nazareth University",
  "St. John Fisher University",
  "Elmira College",
  "Wells College",
  "William Smith College",
  "University of Hartford",
  "University of New Haven",
  "University of Bridgeport",
  "Central Connecticut State University",
  "Eastern Connecticut State University",
  "Southern Connecticut State University",
  "Western Connecticut State University",
  "Albertus Magnus College",
  "Mitchell College",
  "Post University",
  "University of Saint Joseph",
  "Goodwin University",
  "Salve Regina University",
  "Bryant University",
  "Roger Williams University",
  "Johnson & Wales University",
  "University of Massachusetts Boston",
  "University of Massachusetts Dartmouth",
  "University of Massachusetts Lowell",
  "Salem State University",
  "Bridgewater State University",
  "Fitchburg State University",
  "Framingham State University",
  "Westfield State University",
  "Worcester State University",
  "Massachusetts College of Liberal Arts",
  "Merrimack College",
  "Stonehill College",
  "Endicott College",
  "Gordon College",
  "Curry College",
  "Lasell University",
  "Bay Path University",
  "Western New England University",
  "Springfield College",
  "Emerson College",
  "Suffolk University",
  "Wentworth Institute of Technology",
  "Lesley University",
  "Simmons University",
  "Wheaton College (MA)",
  "Clark University",
  "Keene State College",
  "Plymouth State University",
  "Granite State College",
  "Franklin Pierce University",
  "Colby-Sawyer College",
  "New England College",
  "Rivier University",
  "Saint Anselm College",
  "Southern New Hampshire University",
  "University of Southern Maine",
  "University of Maine at Farmington",
  "University of Maine at Augusta",
  "University of Maine at Presque Isle",
  "University of Maine at Machias",
  "Husson University",
  "Thomas College",
  "Saint Joseph's College of Maine",
  "University of New England",
  "Bates College",
  "Bowdoin College",
  "Colby College",
  "Middlebury College",
  "Bennington College",
  "Green Mountain College",
  "Marlboro College",
  "Norwich University",
  "Saint Michael's College",
  "Champlain College",
  "Castleton University",
  "Johnson State College",
  "Lyndon State College",
  "Northern Vermont University",

  // Additional Midwest Schools
  "University of Wisconsin-Eau Claire",
  "University of Wisconsin-La Crosse",
  "University of Wisconsin-Oshkosh",
  "University of Wisconsin-Platteville",
  "University of Wisconsin-River Falls",
  "University of Wisconsin-Stevens Point",
  "University of Wisconsin-Stout",
  "University of Wisconsin-Superior",
  "University of Wisconsin-Whitewater",
  "University of Wisconsin-Parkside",
  "St. Norbert College",
  "Lawrence University",
  "Ripon College",
  "Beloit College",
  "Carroll University",
  "Alverno College",
  "Concordia University Wisconsin",
  "Wisconsin Lutheran College",
  "University of Minnesota Duluth",
  "University of Minnesota Morris",
  "University of Minnesota Rochester",
  "Minnesota State University, Mankato",
  "St. Cloud State University",
  "Winona State University",
  "Minnesota State University Moorhead",
  "Bemidji State University",
  "Southwest Minnesota State University",
  "College of Saint Benedict",
  "Saint John's University (MN)",
  "Gustavus Adolphus College",
  "Augsburg University",
  "Concordia College (MN)",
  "Hamline University",
  "University of St. Thomas (MN)",
  "Bethel University (MN)",
  "North Dakota State University",
  "University of North Dakota",
  "Minot State University",
  "Dickinson State University",
  "Mayville State University",
  "Valley City State University",
  "South Dakota State University",
  "University of South Dakota",
  "Dakota State University",
  "Northern State University",
  "Black Hills State University",
  "Augustana University (SD)",
  "University of Sioux Falls",
  "Wayne State College (NE)",
  "Chadron State College",
  "Peru State College",
  "Doane University",
  "Hastings College",
  "Nebraska Wesleyan University",
  "Concordia University Nebraska",
  "Midland University",
  "York College (NE)",
  "Iowa State University",
  "University of Northern Iowa",
  "Drake University",
  "Grinnell College",
  "Coe College",
  "Cornell College",
  "Luther College",
  "Wartburg College",
  "Central College",
  "Simpson College",
  "Buena Vista University",
  "Dordt University",
  "Northwestern College (IA)",
  "Loras College",
  "Clarke University",
  "University of Dubuque",
  "Mount Mercy University",
  "Grand View University",
  "Upper Iowa University",
  "Graceland University",
  "William Penn University",
  "Central Michigan University",
  "Western Michigan University",
  "Eastern Michigan University",
  "Northern Michigan University",
  "Saginaw Valley State University",
  "Ferris State University",
  "Lake Superior State University",
  "Grand Valley State University",
  "Wayne State University",
  "University of Michigan-Dearborn",
  "University of Michigan-Flint",
  "Michigan Technological University",
  "Kettering University",
  "Calvin University",
  "Hope College",
  "Albion College",
  "Alma College",
  "Adrian College",
  "Hillsdale College",
  "Kalamazoo College",
  "Olivet College",
  "Aquinas College",
  "Cornerstone University",
  "Spring Arbor University",
  "Anderson University (IN)",
  "Butler University",
  "University of Evansville",
  "University of Indianapolis",
  "Valparaiso University",
  "Wabash College",
  "DePauw University",
  "Earlham College",
  "Franklin College",
  "Hanover College",
  "Manchester University",
  "Rose-Hulman Institute of Technology",
  "Saint Mary's College (IN)",
  "Taylor University",
  "Trine University",
  "University of Saint Francis (IN)",
  "Marian University (IN)",
  "Huntington University",
  "Indiana Wesleyan University",
  "Bethel University (IN)",
  "Goshen College",
  "Grace College",
  "Youngstown State University",
  "Cleveland State University",
  "University of Toledo",
  "University of Findlay",
  "Ashland University",
  "Baldwin Wallace University",
  "Capital University",
  "Cedarville University",
  "College of Wooster",
  "Denison University",
  "Heidelberg University",
  "Hiram College",
  "John Carroll University",
  "Kenyon College",
  "Malone University",
  "Marietta College",
  "Mount Vernon Nazarene University",
  "Muskingum University",
  "Ohio Northern University",
  "Ohio Wesleyan University",
  "Otterbein University",
  "University of Mount Union",
  "Ursuline College",
  "Walsh University",
  "Wilmington College (OH)",
  "Wittenberg University",
  "Xavier University",
  "University of Illinois Springfield",
  "University of Illinois Chicago",
  "Illinois State University",
  "Northern Illinois University",
  "Southern Illinois University Carbondale",
  "Southern Illinois University Edwardsville",
  "Western Illinois University",
  "Eastern Illinois University",
  "Governors State University",
  "Northeastern Illinois University",
  "Chicago State University",
  "Augustana College (IL)",
  "Bradley University",
  "DePaul University",
  "Illinois Institute of Technology",
  "Illinois Wesleyan University",
  "Knox College",
  "Lake Forest College",
  "Lewis University",
  "Loyola University Chicago",
  "Millikin University",
  "Monmouth College",
  "North Central College",
  "Principia College",
  "Quincy University",
  "Rockford University",
  "University of St. Francis (IL)",
  "Wheaton College (IL)",
  "Benedictine University",
  "Concordia University Chicago",
  "Dominican University (IL)",
  "Elmhurst University",
  "North Park University",
  "Olivet Nazarene University",
  "Trinity Christian College",
  "Trinity International University",

  // Additional Western Schools
  "Colorado School of Mines",
  "University of Northern Colorado",
  "Colorado Mesa University",
  "Adams State University",
  "Fort Lewis College",
  "Western Colorado University",
  "Colorado Christian University",
  "Regis University",
  "University of Wyoming",
  "Weber State University",
  "Utah State University",
  "Southern Utah University",
  "Dixie State University",
  "Westminster University (UT)",
  "University of Montana",
  "Montana State University",
  "Montana State University Billings",
  "Carroll College (MT)",
  "Rocky Mountain College",
  "University of Great Falls",

  // Other Notable Schools
  "University of Notre Dame",
  "University of Notre Dame",
  "Fordham University",
  "Loyola University Chicago",
  "Loyola Marymount University",
  "Marquette University",
  "DePaul University",
  "Seton Hall University",
  "Creighton University",
  "University of San Diego",
  "University of San Francisco",
  "Saint Louis University",
  "Xavier University",
  "University of Dayton",
  "University of Scranton",
  "Fairfield University",
  "Providence College",
  "Quinnipiac University",
  "Sacred Heart University",
  "Elon University",
  "High Point University",
  "Rollins College",
  "Stetson University",
  "Chapman University",
  "University of the Pacific",
  "University of Tulsa",
  "University of Richmond",
  "Wake Forest University",
  "Belmont University",
  "Lipscomb University",
  "Samford University",
  "Mercer University",
  "Wofford College",
  "Ithaca College",
  "Marist College",
  "Siena College",
  "Bentley University",
  "Babson College",
  "Stonehill College",
  "Assumption University",
  "Hofstra University",
  "Adelphi University",
  "LIU Post",
  "Pace University",
  "The New School",
  "Pratt Institute",
  "Parsons School of Design",
  "School of Visual Arts",
  "Fashion Institute of Technology",
  "Rhode Island School of Design",
  "Savannah College of Art and Design",
  "Art Center College of Design",
  "Otis College of Art and Design",

  // Military Academies
  "United States Military Academy (West Point)",
  "United States Naval Academy",
  "United States Air Force Academy",
  "United States Coast Guard Academy",
  "United States Merchant Marine Academy",

  // Canadian Universities (for border students)
  "University of Toronto",
  "McGill University",
  "University of British Columbia",
  "University of Waterloo",
  "University of Alberta",
  "University of Calgary",
  "Queen's University",
  "Western University",
  "McMaster University",
  "University of Ottawa",
  "Dalhousie University",
  "University of Manitoba",
  "University of Saskatchewan",
  "Simon Fraser University",
  "York University",
  "Ryerson University",
  "Carleton University",

  // UK Universities
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London",
  "London School of Economics",
  "University of Edinburgh",
  "University of Manchester",
  "University of Bristol",
  "University of Warwick",
  "King's College London"
];

// Common course code prefixes organized by department
const COURSE_DEPARTMENTS = {
  "Accounting": ["ACCT", "ACC"],
  "Aerospace Engineering": ["AERO", "AE"],
  "African American Studies": ["AFAM", "AAS", "AFST"],
  "Anthropology": ["ANTH", "ANT"],
  "Arabic": ["ARAB"],
  "Architecture": ["ARCH"],
  "Art": ["ART", "ARTS"],
  "Art History": ["ARTH", "ARH"],
  "Astronomy": ["ASTR", "AST"],
  "Biochemistry": ["BCHM", "BIOC", "BCH"],
  "Bioengineering": ["BIOE", "BE", "BIEN"],
  "Biology": ["BIO", "BIOL"],
  "Biomedical Engineering": ["BME", "BMEN"],
  "Business": ["BUS", "BUSI", "BUSN"],
  "Business Administration": ["BA", "BADM"],
  "Chemical Engineering": ["CHE", "CHME", "CHEN"],
  "Chemistry": ["CHEM", "CHM"],
  "Chinese": ["CHIN", "CHN"],
  "Civil Engineering": ["CE", "CIVE", "CVEN"],
  "Classics": ["CLSS", "CLAS", "CL"],
  "Communication": ["COMM", "COM"],
  "Computer Engineering": ["CMPE", "CPE"],
  "Computer Science": ["CS", "CSC", "CSCI", "CIS", "COMP", "CPSC"],
  "Criminal Justice": ["CJ", "CRIM", "CRJU"],
  "Dance": ["DANC", "DAN"],
  "Data Science": ["DS", "DATA"],
  "Earth Science": ["ERTH", "ESCI", "GEOS"],
  "Economics": ["ECON", "ECO", "EC"],
  "Education": ["EDUC", "ED", "EDU"],
  "Electrical Engineering": ["EE", "ECE", "EECE", "ELEC"],
  "English": ["ENGL", "ENG", "EN"],
  "Environmental Science": ["ENVS", "ENV", "ENVI"],
  "Environmental Engineering": ["ENVE", "EVEN"],
  "Ethnic Studies": ["ETHN", "ES"],
  "Film Studies": ["FILM", "CINE"],
  "Finance": ["FIN", "FINA"],
  "Food Science": ["FDSC", "FSC"],
  "French": ["FREN", "FR"],
  "Gender Studies": ["GNDR", "WMST", "WGS"],
  "Genetics": ["GEN", "GENE"],
  "Geography": ["GEOG", "GEO"],
  "Geology": ["GEOL", "GLY"],
  "German": ["GERM", "GER"],
  "Graphic Design": ["GRPH", "GD"],
  "Health Sciences": ["HLTH", "HSC", "HSCI"],
  "History": ["HIST", "HIS", "HST"],
  "Hospitality Management": ["HOSP", "HTM"],
  "Human Development": ["HDEV", "HD"],
  "Industrial Engineering": ["IE", "ISE", "INEN"],
  "Information Systems": ["IS", "INFS", "MIS"],
  "Information Technology": ["IT", "INFT"],
  "International Relations": ["IR", "INTL"],
  "Italian": ["ITAL", "IT"],
  "Japanese": ["JAPN", "JPN"],
  "Journalism": ["JOUR", "JRN"],
  "Kinesiology": ["KINE", "KIN", "KNES"],
  "Korean": ["KOR", "KORN"],
  "Latin": ["LATN", "LAT"],
  "Law": ["LAW", "LAWS"],
  "Linguistics": ["LING", "LIN"],
  "Management": ["MGMT", "MGT", "MAN"],
  "Marketing": ["MKTG", "MKT", "MRKT"],
  "Materials Science": ["MSE", "MATE", "MATL"],
  "Mathematics": ["MATH", "MTH", "MA"],
  "Mechanical Engineering": ["ME", "MECH", "MEEN"],
  "Media Studies": ["MDIA", "MDST"],
  "Microbiology": ["MICR", "MICRO", "MCB"],
  "Military Science": ["MILS", "MS"],
  "Molecular Biology": ["MOLB", "MB"],
  "Music": ["MUS", "MUSC", "MUSI"],
  "Neuroscience": ["NEUR", "NSCI", "NEU"],
  "Nuclear Engineering": ["NE", "NUCL", "NUEN"],
  "Nursing": ["NURS", "NUR", "NSG"],
  "Nutrition": ["NUTR", "NTR"],
  "Oceanography": ["OCNG", "OCN", "OCEA"],
  "Operations Management": ["OPMT", "OM"],
  "Petroleum Engineering": ["PETE", "PGE"],
  "Pharmacology": ["PHAR", "PHCL"],
  "Philosophy": ["PHIL", "PHL"],
  "Physics": ["PHYS", "PHY", "PH"],
  "Political Science": ["POLS", "POLI", "PS", "PLSC", "POL"],
  "Portuguese": ["PORT", "POR"],
  "Psychology": ["PSYC", "PSY", "PSYCH"],
  "Public Health": ["PUBH", "PH", "HLTH"],
  "Public Policy": ["PUBP", "PP"],
  "Real Estate": ["RE", "REAL"],
  "Religious Studies": ["RELS", "REL", "RELI"],
  "Russian": ["RUSS", "RUS"],
  "Social Work": ["SOCW", "SW", "SOWK"],
  "Sociology": ["SOC", "SOCI"],
  "Spanish": ["SPAN", "SPN", "SP"],
  "Special Education": ["SPED", "SPE"],
  "Speech Pathology": ["SPCH", "SLP", "CSD"],
  "Statistics": ["STAT", "STA", "STATS"],
  "Supply Chain Management": ["SCM", "SCMT"],
  "Theater": ["THTR", "THE", "THEA", "DRAM"],
  "Urban Planning": ["URPL", "UP"],
  "Veterinary Science": ["VET", "VTSC"],
  "Writing": ["WRIT", "WR"]
};

// Generate full course codes (prefix + common numbers)
const COURSE_NUMBERS = ["101", "102", "110", "111", "112", "120", "150", "200", "201", "202", "210", "211", "220", "230", "250", "300", "301", "302", "310", "311", "320", "330", "340", "350", "400", "401", "410", "420", "430", "440", "450", "460", "470", "480", "490", "500", "501", "510", "520", "530", "540", "550", "600", "601", "610", "620"];

// Build a flat list of course codes for autocomplete
function generateCourseCodes() {
  const codes = [];
  for (const [dept, prefixes] of Object.entries(COURSE_DEPARTMENTS)) {
    // Use the first (most common) prefix for each department
    const prefix = prefixes[0];
    COURSE_NUMBERS.forEach(num => {
      codes.push(`${prefix} ${num}`);
    });
    // Also add alternate prefixes with just common numbers
    prefixes.slice(1).forEach(altPrefix => {
      ["101", "102", "201", "202", "301", "302", "401"].forEach(num => {
        codes.push(`${altPrefix} ${num}`);
      });
    });
  }
  return codes;
}

// Get just the department prefixes for quick display
function getDepartmentPrefixes() {
  const prefixes = [];
  for (const [dept, codes] of Object.entries(COURSE_DEPARTMENTS)) {
    codes.forEach(code => {
      prefixes.push({ code, department: dept });
    });
  }
  return prefixes;
}

// Search/filter universities by query
function searchUniversities(query) {
  if (!query) return UNIVERSITIES;
  const lower = query.toLowerCase();
  return UNIVERSITIES.filter(u => u.toLowerCase().includes(lower));
}

// Search/filter course codes by query
function searchCourseCodes(query) {
  if (!query) return Object.keys(COURSE_DEPARTMENTS);
  const lower = query.toLowerCase();
  const results = [];

  for (const [dept, prefixes] of Object.entries(COURSE_DEPARTMENTS)) {
    if (dept.toLowerCase().includes(lower) || prefixes.some(p => p.toLowerCase().startsWith(lower.split(' ')[0]))) {
      // If they typed a number too, filter to matching numbers
      const parts = query.trim().split(/\s+/);
      if (parts.length > 1) {
        const numQuery = parts[1];
        const prefix = prefixes.find(p => p.toLowerCase() === parts[0].toLowerCase()) || prefixes[0];
        COURSE_NUMBERS.filter(n => n.startsWith(numQuery)).forEach(num => {
          results.push(`${prefix} ${num}`);
        });
      } else {
        // Just show department prefixes with common numbers
        const prefix = prefixes[0];
        ["101", "201", "301", "401"].forEach(num => {
          results.push(`${prefix} ${num}`);
        });
      }
    }
  }
  return results;
}
